name: Build shadow JAR for local download

on:
  workflow_dispatch:

jobs:
  build-shadow-jar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Build shadow JAR
        run: |
          ./gradlew :async-query-core:shadowJar

      - name: Upload shadow JAR as artifact
        uses: actions/upload-artifact@v3
        with:
          name: async-query-core-shadow-jar
          path: ./async-query-core/build/libs/*-all.jar
          retention-days: 7